//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyeClinica.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int ID_Cita { get; set; }
        public Nullable<int> ID_Paciente { get; set; }
        public Nullable<int> ID_Medico { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Estado { get; set; }
    
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
